# Generated by Django 5.0.7 on 2024-08-21 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_sale_options_remove_sale_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
