# Generated by Django 5.0.7 on 2024-08-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_sale_options_sale_created_sale_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated',
        ),
    ]
