# Generated by Django 5.0.7 on 2024-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_sale_options_remove_sale_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Nakit'), ('credit_card', 'Kredi Kartı')], default='credit_card', max_length=20),
        ),
    ]
